---

nexus_timezone: 'Europe/Moscow'
nexus_public_hostname: 'nexus.localhost'

nexus_download_dir: '/tmp'
nexus_os_group: 'nexus'
nexus_os_user: 'nexus'
nexus_installation_dir: '/opt'
nexus_data_dir: '/var/nexus'
nexus_tmp_dir: "{{ (ansible_os_family == 'RedHat') | ternary('/var/nexus-tmp', '/tmp/nexus') }}"

#nexus_min_heap_size: "4096M"
#nexus_max_heap_size: "4096M"
#nexus_max_direct_memory: "6G"

nexus_admin_password: "{{ vault_nexus_admin_password }}"

#enable anon
nexus_anonymous_access: true

#first-time empty repos
nexus_delete_default_repos: true

# there is no apt repo , so create it by hand if needed
nexus_config_yum: true
nexus_config_raw: true

#define blobstores
nexus_blobstores:
  - name: artifacts
    path: /var/nexus/blobs/artifacts

  - name: raw-artifacts
    path: /var/nexus/blobs/raw-artifacts

#define repos
nexus_repos_raw_hosted:
  #raw-static
  - name: static-hosted
    version_policy: mixed
    write_policy: allow
    blob_store: raw-artifacts

    #raw-apk-hosted
  - name: apk-hosted
    version_policy: mixed
    write_policy: allow
    blob_store: artifacts

nexus_repos_yum_hosted:
  #yum
  - name: yum-hosted
    repodata_depth: 3
    version_policy: mixed
    write_policy: allow
    blob_store: artifacts

#define privileges
nexus_privileges:
  #raw static
  - name: nx-repository-view-raw-static-hosted-read
    description: "raw-static repo read privilege"
    repository: raw-static
    actions:
      - read

  - name: nx-repository-view-raw-static-hosted-browse
    description: "raw-static repo browse privilege"
    repository: raw-static
    actions:
      - browse

  - name: nx-repository-view-raw-static-hosted-edit
    description: "raw-static repo edit privilege"
    repository: raw-static
    actions:
      - edit

  - name: nx-repository-view-raw-static-hosted-add
    description: "raw-static repo add privilege"
    repository: raw-static
    actions:
      - add

  #yum hosted
  - name: nx-repository-view-yum-yum-hosted-read
    description: "yum-hosted repo read privilege"
    repository: yum-hosted
    actions:
      - read

  - name: nx-repository-view-yum-yum-hosted-browse
    description: "yum-hosted repo browse privilege"
    repository: yum-hosted
    actions:
      - browse

  - name: nx-repository-view-yum-yum-hosted-edit
    description: "yum-hosted repo edit privilege"
    repository: yum-hosted
    actions:
      - edit

  - name: nx-repository-view-yum-yum-hosted-add
    description: "yum-hosted repo add privilege"
    repository: yum-hosted
    actions:
      - add

  #apk hosted
  - name: nx-repository-view-raw-apk-hosted-read
    description: "apk-hosted repo read privilege"
    repository: apk-hosted
    actions:
      - read

  - name: nx-repository-view-raw-apk-hosted-browse
    description: "apk-hosted repo browse privilege"
    repository: apk-hosted
    actions:
      - browse

  - name: nx-repository-view-raw-apk-hosted-edit
    description: "apk-hosted repo edit privilege"
    repository: apk-hosted
    actions:
      - edit

  - name: nx-repository-view-raw-apk-hosted-add
    description: "apk-hosted repo add privilege"
    repository: apk-hosted
    actions:
      - add

#define roles
nexus_roles:
  - id: static_ro
    name: static_ro
    privileges:
      - nx-repository-view-raw-static-hosted-read
      - nx-repository-view-raw-static-hosted-browse
    roles: []

  - id: static_rw
    name: static_rw
    privileges:
      - nx-repository-view-raw-static-hosted-read
      - nx-repository-view-raw-static-hosted-browse
      - nx-repository-view-raw-static-hosted-edit
      - nx-repository-view-raw-static-hosted-add
    roles: []

  - id: yum_ro
    name: yum_ro
    privileges:
      - nx-repository-view-yum-yum-hosted-read
      - nx-repository-view-yum-yum-hosted-browse
    roles: []

  - id: yum_rw
    name: yum_rw
    privileges:
      - nx-repository-view-yum-yum-hosted-read
      - nx-repository-view-yum-yum-hosted-browse
      - nx-repository-view-yum-yum-hosted-edit
      - nx-repository-view-yum-yum-hosted-add
    roles: []

  - id: apk_ro
    name: apk_ro
    privileges:
      - nx-repository-view-raw-apk-hosted-read
      - nx-repository-view-raw-apk-hosted-browse
    roles: []

  - id: apk_rw
    name: apk_rw
    privileges:
      - nx-repository-view-raw-apk-hosted-read
      - nx-repository-view-raw-apk-hosted-browse
      - nx-repository-view-raw-apk-hosted-edit
      - nx-repository-view-raw-apk-hosted-add
    roles: []

  - id: supervisor
    name: supervisor
    privileges:
      - nx-repository-view-*-*-*
    roles: []

#define local users
nexus_local_users:
  - username: anonymous
    first_name: anonymous
    last_name: anonymous
    email: support@company.com
    password: ""
    roles:
      - static_ro

  - username: readonly
    first_name: readonly
    last_name: user
    email: support@company.com
    password: "{{ vault_nexus_readonly_user_password }}"
    roles:
      - yum_ro
      - apk_ro
      - static_ro

  - username: developer
    first_name: developer
    last_name: user
    email: support@company.com
    password: "{{ vault_nexus_developer_user_password }}"
    roles:
      - yum_rw
      - apk_rw
      - static_rw
