---
 nginx_debug_output: true
 nginx_main_template_enable: true
 nginx_main_template:
  template_file: nginx.conf.j2
  conf_file_name: nginx.conf
  conf_file_location: /etc/nginx/
  user: nginx
  worker_processes: auto
  worker_cpu_affinity: auto
  error_level: warn
  worker_connections: 1024
  http_enable: true
  http_settings:
    keepalive_timeout: 65
    cache: false
    rate_limit: false
    keyval: false
  stream_enable: false
  http_global_autoindex: false

 nginx_http_template_enable: true
 nginx_http_template:
  default:
    template_file: http/default.conf.j2
    conf_file_name: default.conf
    conf_file_location: /etc/nginx/conf.d/
    server_name: "{{ nexus_nginx_servername }}"
    https_redirect: true
    listen:
      listen_localhost:
        #ip: localhost # Wrap in square brackets for IPv6 addresses
        port: 80
        opts: [] # Listen opts like http2 which will be added (ssl is automatically added if you specify 'ssl:').

  nexus:
     template_file: http/default.conf.j2
     conf_file_name: nexus.conf
     conf_file_location: /etc/nginx/conf.d/
     server_name: "{{ nexus_nginx_servername }}"
     client_max_body_size: "50m"
     error_page: /usr/share/nginx/html
     autoindex: false
     listen:
       listen_localhost:
         #ip: localhost # Wrap in square brackets for IPv6 addresses
         port: 443
         opts: [] # Listen opts like http2 which will be added (ssl is automatically added if you specify 'ssl:').
     ssl:
      cert: "/etc/nginx/ssl/{{ nexus_nginx_servername}}.crt"
      key: "/etc/nginx/ssl/{{ nexus_nginx_servername}}.key"
      #dhparam: /etc/ssl/private/dh_param.pem
      protocols: TLSv1 TLSv1.1 TLSv1.2
      ciphers: HIGH:!aNULL:!MD5
      prefer_server_ciphers: true
      session_cache: none
      session_timeout: 5m
      disable_session_tickets: false
      stapling: true
      stapling_verify: true
     reverse_proxy:
       locations:
         backend:
           location: /
           proxy_pass: http://nexus_backend
           proxy_set_header:
            header_host:
             name: Host
             value: $host
            header_x_real_ip:
             name: X-Real-IP
             value: $remote_addr
            header_x_forwarded_for:
             name: X-Forwarded-For
             value: $proxy_add_x_forwarded_for
            header_x_forwarded_proto:
             name: X-Forwarded-Proto
             value: $scheme
     upstreams:
       upstream:
         name: nexus_backend
         lb_method: least_conn
         zone_name: backend_mem_zone
         zone_size: 64k
         sticky_cookie: false
         servers:
           nexus_server:
             address: 127.0.0.1
             port: 8081
