{
 "title": "test_dash",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "container uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_container_image:$tag_container_version",
     "groupBy": [
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "container_version" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "docker_container_status",
     "select": [
      [
       { "params": [ "uptime_ns" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "num running containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "load_average 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "cpu User-usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "host: ($tag_host)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "num stopped container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "load_average 5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "disk usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  }
 ]
}