---
apiVersion: v1
kind: Service
metadata:
  name: gitea-lb
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: gitea
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:latest
          ports:
            - containerPort: 3000
              name: gitea
          volumeMounts:
            - mountPath: /data
              name: git-data
      volumes:
        - name: git-data
          hostPath:
            path: /tmp
            type: Directory
