apiVersion: v1
data:
  env: cHJvZA==
  monitor_database: bXlkYg==
  monitor_host: aHR0cDovL2luZmx1eGRiOjgwODY=
  monitor_password: cm9vdA==
  monitor_username: cm9vdA==
kind: Secret
metadata:
  name: telegraf
  namespace: monitoring

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: monitoring
  labels:
    k8s-app: telegraf
data:
  telegraf.conf: |+
    [global_tags]
      env = "$ENV"
    [agent]
      hostname = "$HOSTNAME"
    [[outputs.influxdb]]
      urls = ["$MONITOR_HOST"] # required
      database = "$MONITOR_DATABASE" # required

      timeout = "5s"
      username = "$MONITOR_USERNAME"
      password = "$MONITOR_PASSWORD"

    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
    [[inputs.diskio]]
    [[inputs.kernel]]
    [[inputs.mem]]
    [[inputs.processes]]
    [[inputs.swap]]
    [[inputs.system]]
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
    #[[inputs.kubernetes]]
      #url = "http://127.0.0.1:10255"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: monitoring
  labels:
    k8s-app: telegraf
spec:
  selector:
    matchLabels:
      name: telegraf
  template:
    metadata:
      labels:
        name: telegraf
    spec:
      containers:
        - name: telegraf
          image: docker.io/telegraf:latest
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: "HOST_PROC"
              value: "/rootfs/proc"
            - name: "HOST_SYS"
              value: "/rootfs/sys"
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: telegraf
                  key: env
            - name: MONITOR_USERNAME
              valueFrom:
                secretKeyRef:
                  name: telegraf
                  key: monitor_username
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telegraf
                  key: monitor_password
            - name: MONITOR_HOST
              valueFrom:
                secretKeyRef:
                  name: telegraf
                  key: monitor_host
            - name: MONITOR_DATABASE
              valueFrom:
                secretKeyRef:
                  name: telegraf
                  key: monitor_database
          volumeMounts:
            - name: sys
              mountPath: /rootfs/sys
              readOnly: true
            - name: proc
              mountPath: /rootfs/proc
              readOnly: true
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: utmp
              mountPath: /var/run/utmp
              readOnly: true
            - name: config
              mountPath: /etc/telegraf
      terminationGracePeriodSeconds: 10
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: proc
          hostPath:
            path: /proc
        - name: utmp
          hostPath:
            path: /var/run/utmp
        - name: config
          configMap:
            name: telegraf
