---
grafana_version: 6.7.3

grafana_admin_username: admin
grafana_admin_password: admin

grafana_address: "0.0.0.0"
grafana_port: 3000

grafana_data_dir: "/var/lib/grafana"
grafana_logs_dir: "/var/log/grafana"

grafana_datasources: []
# to properly manage datasources firstly delete it, then re-add
# create entry in `deleteDatasources`, and in `datasources`
#    grafana_datasources:
#      apiVersion: 1
#      deleteDatasources:
#        - name: Prometheus
#          orgId: 1
#      datasources:
#      - name: Prometheus
#        type: prometheus
#        access: proxy
#        url: 'http://127.0.0.1:9090'

grafana_dashboards: []
#    grafana_dashboards:
#      apiVersion: 1
#      providers:
#        - name: 'provider'
#          orgId: 1
#          folder: ''
#          type: file
#          options:
#            path: "{{ grafana_data_dir }}/dashboards"