---
- name: Create/Update datasources
  copy:
    dest: "/etc/grafana/provisioning/datasources/ansible.yml"
    content: "{{ grafana_datasources | to_nice_yaml }}"
    owner: root
    group: grafana
    mode: 0640
  notify: restart grafana
  when: grafana_datasources | length > 0