---
- name : Install Elasticsearch
  hosts: node1
  become: yes
  vars_files:
    - ./roles/setup-elasticsearch/vars/vault.yml

  vars:
    es_log_dir: "/var/lib/elasticsearch/logs"
    es_data_dirs:
     - "/var/lib/elasticsearch/data"
    es_heap_size: "1g"
    es_version: 7.4.2

    es_java_install: true
    update_java: false

    es_enable_xpack: true
    es_xpack_features: ["security"]

    es_api_basic_auth_username: file_admin
    es_api_basic_auth_password: "{{ vault_es_admin_password }}"
    #define config
    es_config:                      #variable to define and inflate as elasticsearch.yml
      node.name: "node1"
      cluster.name: "elastic-cluster"
      discovery.seed_hosts: "10.30.8.37:9300,10.30.8.38:9300"
      http.port: 9200
      transport.port: 9300
      network.host: "0.0.0.0"
      node.data: true
      node.master: true
      cluster.initial_master_nodes: "10.30.8.38"
      bootstrap.memory_lock: false
      xpack.security.transport.ssl.enabled: true
      xpack.security.audit.enabled: true
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
      xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12

#define roles
    es_roles:
      file:
        file_admin_role:
          cluster:
            - all
          indices:
            - names: '*'
              privileges:
                - all
      native:
        telegraf_role:
          cluster:
            - manage_index_templates
            - manage_ilm
            - monitor
          indices:
            - names: 'telegraf-*'
              privileges:
                - all
        filebeat_role:
          cluster:
          - manage_index_templates
          - manage_ilm
          - monitor
          indices:
            - names: 'filebeat-*'
              privileges:
              - all
        filebeat_reader:
          cluster:
            - monitor
          indices:
            - names: 'filebeat-*'
              privileges:
                - read
                - monitor
        telegraf_reader:
          cluster:
            - monitor
          indices:
            - names: 'telegraf-*'
              privileges:
                - read
                - monitor
        admin:
          cluster:
          - all
          indices:
            - names: '*'
              privileges:
              - all
#define users
#todo native users creation will fail in unitialized cluster
    es_users:
      file:
        file_admin:
          password: "{{ vault_es_admin_password }}"
          roles:
            - file_admin_role
      native:
        kibana:
          password: "{{ vault_es_reserved_kibana_password }}"
        admin:
          password: "{{ vault_es_admin_password }}"
          roles:
            - admin
            - kibana_user
        devkibana:
          password: "{{ vault_es_devkibana_password }}"
          roles:
            - filebeat_reader
            - telegraf_reader
            - kibana_user
        filebeat:
          password: "{{ vault_es_filebeat_password }}"
          roles:
            - filebeat_role
        telegraf:
          password: "{{ vault_es_telegraf_password }}"
          roles:
            - telegraf_role
  roles:
    - setup-elasticsearch
