---
- name : Nexus
  hosts: nexus-server
  become: yes
  vars_files:
   - ./vars/vars.yaml
   - ./vars/vault.yaml
   - ./vars/nexus.yaml
   - ./vars/nginx.yaml

  roles:
    - { role: geerlingguy.java  }
    - { role: nexus, tags: ['nexus'] }
    - { role: nginx }

##custom stuff
#todo add apt,apk
#todo move nginx to services
#fix restart
  tasks: 
  - name: Disable SELinux
    selinux:
     state: disabled

  - name: Bind nexus service to 127.0.0.1 only
    lineinfile:
     dest: "{{ nexus_default_settings_file }}"
     regexp: "^application-host=.*"
     line: "application-host=127.0.0.1"
    register: binded

  - name: Tune yum propagation repo
    lineinfile:
     dest: "{{ nexus_default_settings_file }}"
     regexp: "^nexus.yum.createrepo.interval=.*"
     line: "nexus.yum.createrepo.interval=15000"  
  
  - name: Restart nexus
    systemd:
     state: restarted
     name: nexus
    when: binded.changed
