version: "3"

services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources/
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100

#  kafka-exporter:
#    image: danielqsj/kafka-exporter:latest
#    command:
#      - '--kafka.server=35.246.25.132:9092'
#      - '--kafka.server=34.105.182.29:9092'
#      - '--kafka.server=35.105.245.9:9092'
#    ports:
#      - 9308:9308